zapier/kubechecks

.gitignore, Earthfile, pkg/repo/repo.go, pkg/server/hook_handler.go, pkg/vcs_clients/client.go
Previously, when building the git credentials string (`$user:$token@$platform.com`), we were doing it wrong (`$email:$token@gitlab.com`). This PR fixes it, and also enables cross compilation for different architectures (x86 and ARM)
=> Handle errors from Git Setup

localdev/kubechecks/values.yaml, localdev/terraform/gitlab/gitlab.tf, pkg/gitlab_client/pipeline.go, pkg/gitlab_client/status.go
Fixes the following panic, that could happen if the API does not return a pipeline status data.
This change also adds some err logging to API calls.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2993b25]
goroutine 90508 [running]:
github.com/zapier/kubechecks/pkg/gitlab_client.(*Client).CommitStatus(0xc0001206e0, {0x3997eb0?, 0xc000d14d50?}, 0xc0005ec380, 0x3)
/src/pkg/gitlab_client/status.go:12 +0x85
github.com/zapier/kubechecks/pkg/events.(*CheckEvent).CommitStatus(0xc0008783c0, {0x3997eb0, 0xc000d14d50}, 0xc0014c63a0?)
/src/pkg/events/check.go:270 +0xf1
github.com/zapier/kubechecks/pkg/events.(*CheckEvent).ProcessApps(0xc0008783c0, {0x3997eb0, 0xc000715080})
/src/pkg/events/check.go:261 +0xc05 …
```
=> fix: panic in gitlab client when setting commit status

go.mod, go.sum, pkg/gitlab_client/status.go
If multiple external apps update a Gitlab pipeline status for an MR at the same time, Gitlab will often create duplicates instead of merging. This change makes kubechecks retry getting an existing pipeline status a few times (if no pipeline status is found) before adding it's own.
=> Add exp backoff retry when getting Gitlab Pipeline Status

charts/kubechecks/templates/_helpers.tpl, charts/kubechecks/tests/basic_deployment_test.yaml, charts/kubechecks/values.yaml
Currently we don't support arbitrary label setting via Helm; this fixes that
=> Allow common label setting for Helm resources

pkg/argo_client/applications.go
This PR fixes the argo client failing to grab all kinds of cluster versions for all apps. This was due to inconsistency in the data we'd get back from Argo describing the cluster where the app is housed.
=> Fix inconsistent cluster version grabbing

charts/kubechecks/templates/deployment.yaml
We don't carry the labels through to the pods created by the Deployment; this PR fixes that.
=> Apply common labels

charts/kubechecks/Chart.yaml, charts/kubechecks/templates/deployment.yaml, charts/kubechecks/values.yaml
In the Kubechecks Helm chart, the `podSecurityContext` Value is not being used. Instead, the `securityContext` is included both at the pod and container level, which leads to "unsupported field" errors at the pod level. I just changed the deployment template to include the `podSecurityContext`.
I would also suggest providing sane defaults for both, instead of commenting them out in the values.yaml. Of course, feel free to revert this. ;)
Cheers!
=> [Helm chart] `.Values.podSecurityContext` is not used

.github/workflows/on_pull-request_docs.yaml, .github/workflows/on_pull_request.yaml, .github/workflows/on_pull_request_go.yaml, .tool-versions, Earthfile, cmd/controller_cmd.go, cmd/flags.go, cmd/flags_test.go, cmd/root.go, cmd/version.go, docs/usage.md, docs/usage.md.tpl, hacks/env-to-docs.go
our docs have gotten quite out of sync w/ the actual application; this should enforce that they stay up to date
here's the new output:
```
Usage:
kubechecks [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
controller  Start the VCS Webhook handler.
help        Help about any command
version     List version information
Flags:
--argocd-api-insecure                  Enable to use insecure connections to the ArgoCD API server. (KUBECHECKS_ARGOCD_API_INSECURE)
--argocd-api-server-addr string        ArgoCD API Server Address. (KUBECHECKS_ARGOCD_API_SERVER_ADDR) (default "argocd-server")
--argocd-api-token string              ArgoCD API token. (KUBECHECKS_ARGOCD_API_TOKEN)
-h, --help                                 help for kubechecks
-l, …
```
=> add docs option generation into the pipeline

pkg/vcs_clients/message.go
without this, the comments bounce around for large MRs
=> sort the names of the apps

pkg/validate/validate.go, pkg/vcs_clients/message.go
Manifests of kind CustomResourceDefinition fail validation. Here's a fix as stated here: https://github.com/yannh/kubeconform/issues/100#issuecomment-1096832969
=> Add fallback schema location for CustomResourceDefinition Kinds

.github/ct.yaml, .gitignore, charts/kubechecks/Chart.yaml, charts/kubechecks/templates/hpa.yaml, charts/kubechecks/tests/autoscaling_test.yaml
=> support multiple HPA versions

pkg/aisummary/diff_summary.go
=> Update OpenAI GPT4 model

charts/kubechecks/Chart.yaml, charts/kubechecks/templates/deployment.yaml, charts/kubechecks/values.yaml
This PR adds the ability to add annotations to the deployment's pod template.
Use cases for this are plenty and `podAnnotations` is a common option in Helm charts. In our case, we need these to select a less restrictive [pod security standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/) for the Kubechecks pod, since it needs to run as root.
I have no real preference whether the key should be `.Values.podAnnotations` or `.Values.deployment.podAnnotations`. I just placed it next to the key for deployment annotations.
=> Support pod annotations in Helm chart

.github/workflows/maintenance.yaml, .github/workflows/on_pull-request_closed.yaml, .github/workflows/on_pull_request.yaml, .github/workflows/on_push_to_main.yaml
Build an image per PR, keep it up to date, and delete it when the PR closes.
This does 4 things:
- on PR create/update, build and push an image called `0.0.0-pr##` (named this way b/c ghcr requires semver compatible tags)
- on PR close, delete the `0.0.0-pr##` tag
- once a week, delete untagged images
- when publishing to main, build and push an image tagged via `git describe` (something like `$LAST_TAG-$NUMCOMMITS-g$HASH`)
=> make it easier to test pull request images

pkg/affected_apps/argocd_matcher.go, pkg/affected_apps/argocd_matcher_test.go, pkg/affected_apps/best_effort.go, pkg/affected_apps/best_effort_test.go, pkg/affected_apps/config_matcher.go, pkg/affected_apps/matcher.go, pkg/config/app_directory.go, pkg/config/app_directory_test.go, pkg/config/walk_kustomize_files_test.go, pkg/events/check.go, pkg/repo/repo.go, pkg/server/hook_handler.go
=> support non-default branches in apps

pkg/repo/repo.go
This should resolve errors like:
```
2:42AM ERR unable to clone repository, error="exec: Stdout already set"
```
=> This can't be set if we call 'StdoutPipe' or 'CombinedOutput' later

pkg/config/walk_kustomize_files.go
github.com is a special case. there's probably more, not sure where kustomize's source code defines them though.
=> these urls shouldn't be walked

pkg/commitState.go, pkg/conftest/conftest.go, pkg/events/check.go, pkg/message.go, pkg/message_test.go, pkg/vcs/client.go, pkg/vcs/github_client/client.go, pkg/vcs/github_client/emoji.go, pkg/vcs/github_client/message.go, pkg/vcs/gitlab_client/emoji.go, pkg/vcs/gitlab_client/message.go, pkg/vcs/gitlab_client/status.go
=> use vcs-specific emoji

pkg/diff/diff.go, pkg/events/check.go
This supports scenarios where, for example, you add a new helm values file to the argo application along w/ the actual changes in the same PR.
=> re-run apps when they're updated

pkg/diff/diff.go, pkg/events/check.go, pkg/message.go, pkg/message_test.go
we don't know if they've already been parsed, so we mark them as deleted, then skip them when building the results.
=> skip apps that are being deleted

go.mod, go.sum, pkg/aisummary/diff_summary.go
1. this model has trained data up to Dec 2023
2. allows higher token input of 128,000. A significant improvement from the current GPT4's limit of 8192 tokens.
=> Update the GPT model to GPT4Turbo0125

pkg/events/check.go, pkg/events/check_test.go, pkg/git/manager.go, pkg/git/repo.go, pkg/git/repo_test.go
when a repo is cloned, it could be cloned with either a named branch OR `HEAD`. in practice, they could refer to the same branch, and this MR fixes the code so they can be referenced interchangeably, when appropriate.
=> ensure that head refs are dealt with properly

cmd/flags.go, cmd/root.go, docs/usage.md, pkg/config/config.go, pkg/events/check.go, pkg/events/runner.go
When diffing large amounts of apps, kubechecks could get into a deadlock. This should increase the limits to some fairly reasonable numbers, but also makes the configurable in case they need to be increased further.
=> increase channels size and goroutine limits

pkg/msg/message.go
=> Output a better error message when nothing has changed

pkg/checks/diff/diff.go
this behavior causes confusion and kubechecks loses some value in not checking these
=> do not skip hooks when diffing, conforming, etc

pkg/argo_client/client.go, pkg/argo_client/manifests.go, pkg/events/check.go, pkg/events/runner.go, pkg/events/worker.go, pkg/msg/message.go, pkg/msg/message_test.go
report panics in app checks
protect against some concurrency issues that cause panics and errors
also bring back the footer
=> panic related improvements

pkg/checks/diff/diff.go
argocd returns 403 if an app doesn't exist; this logic was just wrong
=> fix: ignore the 403 returned from argocd when creating new app

cmd/processors.go, cmd/root.go, docs/usage.md, pkg/checks/diff/diff.go, pkg/checks/hooks/check.go, pkg/checks/hooks/check_test.go, pkg/checks/hooks/grouped.go, pkg/config/config.go
=> return to hiding hooks in the diff, render seperately

pkg/affected_apps/argocd_matcher.go, pkg/appdir/appset_directory.go, pkg/appdir/appset_directory_test.go
applicationsets was checking the manifest was targeting main, however there are cases where targetRevision may be using template e.g. `{{ .values.target }}` This causes the check to fail and does not perform applicationset checks.
This PR removes the check as this check is only required on the applications not applicationsets.
fixes https://github.com/zapier/kubechecks/issues/269
=> remove application set revision check.

cmd/root.go, docs/usage.md, pkg/argo_client/client.go, pkg/config/config.go, pkg/config/config_test.go
=> feat(argocd client): Add handling of argocd-api-plaintext option

cmd/locations.go, go.mod
This is to address [CVE-2024-41110](https://github.com/advisories/GHSA-v23v-6jw2-98fq)
Docker package was used to check for git urls.
this PR implements the fork inside locations.go instead of pulling entire package.
=> remove docker package: CVE-2024-41110

cmd/locations.go, cmd/locations_test.go
add url parse validator.
add gitlab as one of prefix
=> unit test for giturl check

pkg/argo_client/manifests.go
If the helm source has `ignoreMissingValuesFiles = true` kubechecks should ignore values file copy errors where the file is not found.
In one of our multi source appsets we reference a bunch of optional values files that allow overriding values at different levels / layers / environments / tiers / providers / whatever.
```
failed to generate manifests: failed to package application: failed to copy referenced value file: "$values/apps/aws-provider/default.values.yaml": open /tmp/kubechecks-repo-4238925250/apps/aws-provider/default.values.yaml: no such file or directory
```
=> handle source.spec.helm.ignoreMissingValuesFiles = true

cmd/root.go, docs/usage.md
When trying to use kubechecks with enterprise github I get the following error:
```
error="failed to create vcs client: failed to get user: GET https://api.github.com/user: 401 Bad credentials []"
```
```
configMap:
create: true
env:
KUBECHECKS_VCS_BASE_URL: https://<redacted>/
KUBECHECKS_VCS_UPLOAD_URL: https://<redacted>/
KUBECHECKS_VCS_TYPE: github
```
Meaning it is still trying to connect to github proper. 
After checking the source, I believe the `KUBECHECKS_VCS_UPLOAD_URL` isn't being parsed, though is referenced in the Github client - https://github.com/zapier/kubechecks/blob/35dfcf6cf96c66d4893be723f5db45ebd629b047/pkg/vcs/github_client/client.go#L64
I wasn't able to properly get the local testing environment fully working due to ngrok mitm issues, but I believe this should …
=> fix: add missing `vcs-upload-url` flag for enterprise github

charts/kubechecks/Chart.yaml, charts/kubechecks/templates/deployment.yaml, charts/kubechecks/templates/service.yaml, charts/kubechecks/values.schema.json
Currently, there is no option to configure Kubecheck to authenticate against OCI registries like GCR/GAR. By adding support for initContainers, users can set up credential helpers such as docker-credential-gcr to generate a config.json for Docker authentication, the initContainer  can also copies the docker-credential-gcr binary into the main Kubecheck container, allowing it to successfully fetch tokens and authenticate
=> Add initContainers support

.github/workflows/on_release_published.yaml
update action to push image when built by on_release_published.yaml
=> ci build change

charts/kubechecks/Chart.yaml, charts/kubechecks/templates/role.yaml, charts/kubechecks/templates/rolebinding.yaml
1. change to use kubechecks.fullname for the role name and role binding name.
=> feat: role and rolebinding template change to allow name override.

charts/kubechecks/Chart.yaml, charts/kubechecks/templates/rolebinding.yaml
1. change roleRef.name to use variable
=> fix: role binding ref name reference change.

pkg/affected_apps/argocd_matcher.go, pkg/affected_apps/argocd_matcher_test.go, pkg/app_watcher/app_watcher_test.go, pkg/appdir/app_directory.go, pkg/appdir/app_directory_test.go, pkg/appdir/appset_directory.go, pkg/appdir/appset_directory_test.go, pkg/appdir/vcstoargomap.go, pkg/appdir/vcstoargomap_test.go, pkg/appdir/walk_kustomize_files.go, pkg/events/check.go
Turns out there was both ProcessApp and AddApp, only one of which was ever correct. This combines those functions, reduces the scope of a few other functions, and renames some to make it clear they deal with AppSets and not Apps.
=> Fix: helm apps wouldn't diff if values file was outside of chart

localdev/kubechecks/values.yaml
Since the grpc update and others, tilt local dev is not starting up correctly.
This will fix the issue of not starting up.
1. specify the argocd namespace to kubechecks.
2. set GRPC_ENFORCE_ALPN_ENABLED to false as tilt-argocd server does not have a valid cert
=> fix: tilt local development

pkg/argo_client/client.go, pkg/argo_client/manifests.go
Issues like #349 seem to indicate that our requests are overloading specific pods, rather than utilizing the whole cluster.
=> use round robin to distribute requests to all repo server pods

Earthfile, pkg/argo_client/manifests.go, pkg/argo_client/manifests_test.go
- update built in kustomize to 5.6.0
- add dependency walk to kustomize.yaml file
=> fix: kustomize dependancy handling

pkg/argo_client/manifests.go, pkg/config/config.go
Hello,
some tools like `git-crypt` require to receive the repository metadata as well and are commonly used to encrypt sensitive data alongside k8s configurations, so I think this should be supported.
=> feat: add flag to include .git

pkg/kustomize/process.go, pkg/kustomize/process_test.go
current kustomization.yaml walk does not parse the helmCharts section. 
This PR is to add ability to add these values file per chart and send to the argo-cd-repo server.
=> feat: improve kustomization walk for helmCharts section

pkg/kustomize/process.go, pkg/kustomize/process_test.go
Turns out that kustomize can point to a folder full of manifests, in which case we need to track the full directory. Alternately, if a folder has a `kustomization.yaml` file, we don't need to track the folder, only the files in it.
=> handle kustomize folders vs folder of manifests

charts/kubechecks/Chart.yaml, charts/kubechecks/templates/deployment.yaml, charts/kubechecks/values.schema.json, charts/kubechecks/values.yaml
When using ArgoCD in a full gitops context, revision history limit clutters the UI with unused ReplicaSets. Allowing configuration of the revision history limit allows users to set this to a different value, such as `0`. With a revision history limit of `0`, Kubernetes will auto-remove any ReplicaSet other than the current active ReplicaSet. I have set a default of `10` so the change is backwards compatible, this is the Kubernetes default.
=> feat: Support changing revisionHistoryLimit from kubernetes default of 10

cmd/root.go, docs/usage.md, localdev/kubechecks/values.yaml, pkg/config/config.go, pkg/events/check.go, pkg/msg/message.go, pkg/msg/message_test.go, pkg/vcs/github_client/message.go, pkg/vcs/gitlab_client/message.go
Allow multiple kubechecks with the same token. 
When running multiple kubechecks with the same token, comments are hidden by one of the kubechecks regardless of which instance created it. Take for instance you have two argocd instances each with different kubechecks running. Both argocds read from a single centralised repo. When you make an MR, the kubechecks from argocd A, will hide the comments from the kubechecks on argocd B. Hence the need for this feature.
=> Allow multiple kubechecks instances with the same token

cmd/locations.go, cmd/locations_test.go, cmd/root.go, docs/usage.md, localdev/kubechecks/values.yaml, pkg/config/config.go, pkg/events/check.go, pkg/git/manager.go, pkg/git/repo.go, pkg/utils.go
This adds support for shallow cloning repos. 
With every hook/request, kubechecks clone the full repo. This can become very expensive for large repositories. 
Shallow cloning allows us to limit the cloning to just the commits we need.
=> feat: add support for shallow cloning repos

pkg/events/check.go
Currently, these two messages are printed in a code block like this:
```
No changes
```
Instead of with the markdown like this
> ## Kubechecks %s Report
> No changes
This PR should fix it.
=> fix: message format

pkg/appdir/vcstoargomap.go, pkg/kustomize/process.go, pkg/kustomize/process_test.go
This was causing apps to be seen as owning their parent directories. In other words, an app called "argocd" in a repo folder of "/apps/infrastructure/production/argocd" was seen to be changed any time any file was changed under "/apps/infrastructure/production", causing far more work to be done than is necessary in some circumstances.
Fixes #372
=> fix: must parse kustomization.yaml

.golangci.yml, .tool-versions, cmd/flags_test.go, cmd/locations.go, cmd/process.go, cmd/root.go, docs/usage.md, go.mod, pkg/appdir/app_directory.go, pkg/appdir/appset_directory.go, pkg/argo_client/applications.go, pkg/argo_client/kustomize.go, pkg/argo_client/manifests.go, pkg/checks/diff/diff.go, pkg/checks/preupgrade/kubepug.go, pkg/config/config.go, pkg/events/check.go, pkg/generator/cluster.go, pkg/git/repo.go, pkg/kustomize/process.go, pkg/kustomize/process_test.go, pkg/utils.go, tools/dump_crds/go.mod
- add extra tests
- add some comments to function
-  fix args spelling error `max-concurrenct-checks` -> `max-concurrent-checks`
- Add namespace to `generated-store` -> `kubepug-generated-store`
- Fix golang-ci lint issues by running `golangci-lint run --fix` and also manually fixing other cases.
=> chore: upgrade go version, add tests and comments, and fix arg names

.github/dependabot.yml
1. group minor & patch updates (over 1.0) into a single MR
2. all others get their own MRs
=> clean up dependabot configuration

pkg/git/repo.go, pkg/git/repo_test.go
Run `git remote set branch "*"` after shallow clone
Closes #407
=> feat: remote set branch after shallow clone

.github/workflows/on_pull_request_go.yaml, .tool-versions, Earthfile, go.mod, go.sum
The current version of kubeconform doesn't support the necessary duration formats used by Kubernetes. This is fixed in version 0.7.0 by this [PR](https://github.com/yannh/kubeconform/commit/e65429b1e5990dd019ebb7b5642dcd22a3e9cd13)
Before:
After:
=> Bump kubeconform to v0.7.0

pkg/vcs/github_client/client.go
If logging is set to DEBUG, when using Github App, access token and other details are displayed in logs during the token refresh process.
2025-08-28 18:08:14.2634:08PM INF refreshing github app token process=refresh-token
2025-08-28 18:08:14.4764:08PM DBG building command args=["config","--global","user.email","kubechecks@zapier.com"]
2025-08-28 18:08:14.4794:08PM DBG building command args=["config","--global","user.name","kubechecks"]
2025-08-28 18:08:14.4824:08PM DBG building command args=["https://x-access-token:foobar@github.com"]
2025-08-28 18:08:14.4834:08PM DBG building command args=["config","--global","credential.helper","store"]
fixes https://github.com/zapier/kubechecks/issues/456
=> fix: censor githubApp token in logs
